const ADD_DOGS = "ADD_DOGS";
const ADD_DOGS_DB = "ADD_DOGS_DB";
const ADD_DOGS_NAME = "ADD_DOGS_NAME";
const ADD_DOGS_ONSEARCH = "ADD_DOGS_ONSEARCH";
const ADD_TEMPERAMENTS = " ADD_TEMPERAMENTS";
const FILRTER_ORIGIN = "FILTER_ORIGIN";
const FILTER_TEMPERAMENT = "FILTER_TEMPERAMENT";
const FILTER_ORDER = "FILTER_ORDER";
const FILTER_WEIGHT = "FILTER_WEIGHT";

module.exports = {
  ADD_DOGS,
  ADD_TEMPERAMENTS,
  FILRTER_ORIGIN,
  FILTER_TEMPERAMENT,
  FILTER_ORDER,
  FILTER_WEIGHT,
  ADD_DOGS_NAME,
  ADD_DOGS_ONSEARCH,
  ADD_DOGS_DB,
};
